# This is the parameter specification of the JTK software.

## Required parameters. Please set them appropriately.
### The input file. Fasta and FASTQ is supported. Compressed files are not supported.
input_file = "input.fa" 
### The sequencing platform. ONT, CCS, or CLR.
read_type = "ONT"


## Recommended parameters. Please set them if you have (any) estimation.
### Output directory
out_dir = "./"
### Output prefix. The final assembly would be `out_dir/prefix.gfa`.
prefix = "temp"
### The number of threads.
threads = 1
### The number of the chunks. Usually, 2 x (Genome size) / (chunk_len) would be OK.
take_num = 2500
### If true, the consensus would be polished by JTK.
to_polish = true
### Resuming. If `out_dir` have JSON files with the specified prefix, JTK re-uses it.
resume = false


## Tunable parameters. Sometimes tuning these parameters would improve the assembly.
### Please un-comment this parameter if you have a esimation of the coverage, 
### and the specified region is highly repetitive.
# haploid_coverage = 20
### The length of the k-mers used to mask repeats.
kmersize = 12
### Upper [top_freq] k-mers would be masked as repeats.
top_freq = 0.001
### Purge chunks having more than [purge_copy_num] phases.
purge_copy_num = 9
### Discard chunks with occurence more than or equal to [upper].
upper = 400
### Discard chunks with occurence less than or equal to [lower].
lower = 4
### # of reads required to span homozygous region.
### Lowering this value would produce more "phased" assembly.
### But they would more likely to switching errors.
min_span = 2
### Verbose level. 2 is debug more, 3 is trace mode. I recommend to use 2.
verbose = 2


## Parameters for reproducibility. Usually, you do not need to modify them.
### Seed for a pseudorandom number generator.
seed = 32149380
### The length of chunks.
chunk_len = 2000
### The margin between adjacent chunks in base pair.
margin = 500
### filter out unit having more than [exclude] repetitiveness."
exclude = 0.8
### Min-counts of the k-mer.
min_count = 10
### We pick the top [component_num] largest connected component for assembly.
component_num = 1
### Compress contigs less than [compress_contig] x [chunk_len].
compress_contig = 15
### The size of the window in consensus
polish_window_size = 2000
### Minimum required log likelihood ratio to span region. Should be positive!
min_llr = 1
### Filter lower [supress_frac] weak clusters.
supress_ari = 0.4
### Match/Mismatch penalty for clustering
match_ari = 4.0
mismatch_ari = -1.0
### The minimum required spanning reads to compute the weakness of a cluster.
required_count = 7
