[package]
name = "haplotyper"
version = "0.1.0"
authors = ["ban-m <ban-m@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
definitions = {path = "../definitions"}
log = "*"
env_logger = "*"
bio_utils = {git = "https://github.com/ban-m/bio_utils.git", branch = "master"}
dirichlet_fit = {git = "https://github.com/ban-m/dirichlet_fit.git"}
serde = {version = "1.0", features = ["derive"]}
rayon = "*"
rand = "*"
rand_xoshiro = "*"
rand_distr = "*"
poa_hmm = {git = "https://github.com/ban-m/partial_order_alignment.git", branch = "master", features = ["poa_simd"]}
de_bruijn_graph = {git = "https://github.com/ban-m/de_bruijn_graph.git", branch = "hla_module"}
nalgebra  = "*"
serde_json = "*"
histgram_viz = {git = "https://github.com/ban-m/histgram_viz", branch = "master"}
mcl = {path = "../mcl"}
gfa = {git = "https://github.com/ban-m/gfa_rust.git", branch = "master"}
edlib_sys = {git = "https://github.com/ban-m/edlib-sys.git", branch = "master"}
path_phasing = {git = "https://github.com/ban-m/pathhap.git", branch = "main"}
bytecount = "*"
# kiley = {git = "https://github.com/ban-m/kiley.git", branch = "master"}
kiley = {path = "../../kiley"}
